services:
  library_front:
    build: .
    container_name: library_front
    env_file:
      - .env
    ports:
      - "3000:3000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.library_front_https.redirectscheme.scheme=https
      - traefik.http.routers.library_front.entrypoints=web
      - traefik.http.routers.library_front.middlewares=library_front_https@docker
      - traefik.http.routers.library_front.rule=Host(`library-front.server_name.youdomain`)
      - traefik.http.routers.library_front_https.entrypoints=websecure
      - traefik.http.routers.library_front_https.rule=Host(`library-front.server_name.youdomain`)
      - traefik.http.routers.library_front_https.tls=true
      - traefik.http.routers.library_front_https.tls.certresolver=le
networks:
  default:
    external:
      name: traefik_default